### ISSUE TITLE
Modernize and update EDI ESB camel

### ISSUE THREAD

**Issue by haneloreianoseck** [metasfresh/metasfresh-edi#1]
### Is this a bug or feature request?

FR

### What is the expected or desired behavior?

Should work as until now but with:
- updated java and camel version
- rabbitmq instead of activemq
- use spring boot

**Comment by metas-ts** [comment]
@haneloreianoseck FYI i just
* renamed this repo to `metasfresh-edi`
* created a new repo https://github.com/metasfresh/metasfresh-esb-legacy with this repo's current `master` branch.
